# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d37701c35c34b1fd2fb51ae4756686eb"
application_url = "https://concord-dining-journalist-eyed.trycloudflare.com"
embedded = true
name = "app-02"
handle = "app-1601"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://concord-dining-journalist-eyed.trycloudflare.com/auth/callback",
  "https://concord-dining-journalist-eyed.trycloudflare.com/auth/shopify/callback",
  "https://concord-dining-journalist-eyed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
