# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b400207d5fa8454dc2f1bb103b9c0528"
application_url = "https://commentary-besides-mounted-seems.trycloudflare.com"
embedded = true
name = "app-02"
handle = "app-1601"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://commentary-besides-mounted-seems.trycloudflare.com/auth/callback",
  "https://commentary-besides-mounted-seems.trycloudflare.com/auth/shopify/callback",
  "https://commentary-besides-mounted-seems.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
