# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbed82e4b8d28f96a4f5de0e316c0066"
application_url = "https://flashing-january-usage-customized.trycloudflare.com"
embedded = true
name = "remix-app-store"
handle = "remix-app-store-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://flashing-january-usage-customized.trycloudflare.com/auth/callback",
  "https://flashing-january-usage-customized.trycloudflare.com/auth/shopify/callback",
  "https://flashing-january-usage-customized.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
